Repository AI-ary/frontend, pull requests merged in 2023-10, with the labels that each got.

#54 [Fix/#52] 달리 액박 해결
  package.json
  public/images/eraser.svg
  public/images/undo.svg
  src/apis/auth.ts
  src/pages/WriteDiary/WriteGrimPage.tsx
  src/pages/WriteDiary/components/DalleChoice.tsx
  src/pages/WriteDiary/components/DiaryContent.tsx
  src/pages/WriteDiary/components/Drawing.tsx
  src/pages/WriteDiary/components/GrimChoice.tsx
  src/styles/diary/diarywrite.style.ts
  yarn.lock
Labels: 오류수정

#55 [Feat/#53] 책갈피 구현
  index.html
  src/apis/auth.ts
  src/pages/WriteDiary/components/Drawing.tsx
  src/pages/WriteDiary/components/GrimChoice.tsx
  src/styles/diary/diarywrite.style.ts
  src/theme/GlobalStyle.ts
Labels: 기능구현

#56 [Feat/#51] 프로필 API 연동 및 모달창 구현
  public/images/check.svg
  src/App.tsx
  src/apis/auth.ts
  src/apis/writeDiary.ts
  src/components/Modal.tsx
  src/components/bookshape/ClosedBook.tsx
  src/index.css
  src/pages/Auth/SignIn/components/SignInForm.tsx
  src/pages/Auth/SignUp/components/SignUpForm.tsx
  src/pages/Auth/components/Logout.tsx
  src/pages/DiaryList/components/DiaryList.tsx
  src/pages/Main/MemberMainPage.tsx
  src/pages/Main/NonMemberMainPage.tsx
  src/pages/WriteDiary/components/DiaryContent.tsx
  src/pages/WriteDiary/components/Manuscript.tsx
  src/store/store.ts
  src/styles/bookshape/closedbook.style.ts
  src/styles/common.style.ts
  src/styles/modal.style.ts
Labels: 기능구현

#58 [Design/#57] 자잘한 디자인 수정
  src/components/Navbar.tsx
  src/pages/DiaryList/components/DiaryList.tsx
  src/pages/Search/components/SearchCalender.tsx
  src/pages/WriteDiary/components/DiaryContent.tsx
  src/styles/diary/diarysearch.style.ts
  src/styles/diary/diarywrite.style.ts
  src/theme/theme.ts
Labels: 퍼블리싱

#60 [Feat/#59] 로딩창 및 AI 부분 모달 구현
  src/apis/dalle.ts
  src/apis/konlpy.ts
  src/components/KonlpyLoading.tsx
  src/components/Modal.tsx
  src/components/Navbar.tsx
  src/index.css
  src/pages/WriteDiary/components/DiaryContent.tsx
  src/store/store.ts
  src/styles/modal.style.ts
  src/theme/GlobalStyle.ts
Labels: 기능구현

#63 [Fix/#61] 토큰 재발급, 중복 클릭 에러 해결, 북마크, 검색 내용 없을 시, 달리 이미지 오류 수정
  src/apis/baseAxios.ts
  src/apis/searchDiary.ts
  src/pages/Auth/SignIn/components/SignInForm.tsx
  src/pages/DiaryList/GrimListPage.tsx
  src/pages/Search/DiarySearchPage.tsx
  src/pages/WriteDiary/components/DiaryContent.tsx
  src/styles/bookshape/closedbook.style.ts
  src/styles/bookshape/opendbook.style.ts
  src/styles/diary/diary.style.ts
Labels: 오류수정

#64 [design/#62] 로딩창 이미지 수정
  dist/assets/index-2dbba62c.js
  dist/assets/index-8fdf0911.css
  dist/assets/index-9278c311.css
  dist/assets/index-bae3f1db.js
  dist/images/drawinglogo.gif
  dist/index.html
  public/images/drawinglogo.gif
  src/apis/dalle.ts
  src/apis/konlpy.ts
  src/apis/writeDiary.ts
  src/components/KonlpyLoading.tsx
  src/components/Loading.tsx
  src/index.css
  src/pages/WriteDiary/WriteGrimPage.tsx
  src/pages/WriteDiary/components/DiaryContent.tsx
  src/styles/diary/diarywrite.style.ts
  src/styles/modal.style.ts
Labels: 퍼블리싱

#68 [design/#65] 소개 페이지 퍼블리싱
  public/images/guidekonlpy.png
  public/images/guiderealdiary1.png
  public/images/guiderealdiary2.png
  public/images/guidetheme1.png
  public/images/guidetheme2.png
  public/images/guidetheme3.png
  src/App.tsx
  src/components/Navbar.tsx
  src/components/bookshape/ClosedBook.tsx
  src/components/bookshape/OpenBookLeft.tsx
  src/pages/DiaryList/GrimListPage.tsx
  src/pages/Introduce.tsx
  src/pages/Search/DiarySearchPage.tsx
  src/pages/WriteDiary/WriteGrimPage.tsx
  src/styles/bookshape/opendbook.style.ts
  src/styles/introduce.style.ts
  src/theme/GlobalStyle.ts
Labels: 퍼블리싱
