Repository AI-ary/frontend, pull requests merged in 2023-09, with the labels that each got.

#40 [chore/#26] 프론트 도커파일 수정
  .dockerignore
  Dockerfile
  dockerfile.prod
  package-lock.json
  vite.config.ts
Labels: 환경설정

#41 [Design/#39] 검색창, 검색페이지 퍼블리싱
  public/images/delete.svg
  public/images/person.svg
  public/images/search.svg
  public/images/share.svg
  src/components/Navbar.tsx
  src/pages/DiaryList/components/DiaryList.tsx
  src/pages/Search/DiarySearchPage.tsx
  src/pages/Search/components/SearchCalender.tsx
  src/styles/diary/diary.style.ts
  src/styles/diary/diarysearch.style.ts
  src/styles/diary/diarywrite.style.ts
  src/theme/GlobalStyle.ts
Labels: 퍼블리싱

#42 [Feat/#38] 닫는 기능 구현 및 화면 크기에 따라 책 미는 간격 조정
  src/components/bookshape/Bookmark.tsx
  src/components/bookshape/OpenBookLeft.tsx
  src/components/bookshape/OpenBookRight.tsx
  src/pages/DiaryList/GrimListPage.tsx
  src/pages/Main/MemberMainPage.tsx
  src/pages/Main/components/Modal.css
  src/styles/bookshape/closedbook.style.ts
  src/styles/bookshape/opendbook.style.ts
  src/theme/GlobalStyle.ts
Labels: 기능구현

#45 [Feat/#44] 로그인, 회원가입 api 연동
  src/apis/auth.ts
  src/components/bookshape/Bookmark.tsx
  src/components/bookshape/OpenBookLeft.tsx
  src/index.css
  src/pages/Auth/SignUp/components/SignUpForm.tsx
  src/pages/Auth/components/Logout.tsx
  src/pages/Main/MemberMainPage.tsx
  src/styles/bookshape/opendbook.style.ts
  src/styles/diary/diarylist.style.ts
  src/theme/theme.ts
Labels: 기능구현

#49 [Feat/#48] 태블릿 반응형 수정 및 프로필 api 연동
  src/apis/auth.ts
  src/components/bookshape/OpenBookLeft.tsx
  src/pages/Auth/SignIn/SignInPage.tsx
  src/pages/Auth/SignIn/components/SignInForm.tsx
  src/pages/Auth/SignUp/SignUpPage.tsx
  src/pages/Auth/components/Logout.tsx
  src/pages/Main/MemberMainPage.tsx
  src/pages/Main/components/Modal.css
  src/styles/auth/auth.style.ts
  src/styles/bookshape/opendbook.style.ts
  src/theme/GlobalStyle.ts
Labels: 기능구현

#50 [Feat/#47] AI(konlpy, dall-e), 일기 검색 api 연동
  src/apis/auth.ts
  src/apis/baseAxios.ts
  src/apis/dalle.ts
  src/apis/diaryList.ts
  src/apis/konlpy.ts
  src/apis/searchDiary.ts
  src/apis/writeDiary.ts
  src/pages/DiaryList/GrimListPage.tsx
  src/pages/DiaryList/components/DiaryList.tsx
  src/pages/Search/DiarySearchPage.tsx
  src/pages/Search/components/SearchCalender.tsx
  src/pages/WriteDiary/components/DiaryContent.tsx
  src/pages/WriteDiary/components/Drawing.tsx
  src/pages/WriteDiary/components/GrimChoice.tsx
  src/store/store.ts
  src/styles/diary/diary.style.ts
  src/styles/diary/diarywrite.style.ts
Labels: 기능구현
