Repository AI-ary/frontend, pull requests merged in 2023-08, with the labels that each got.

#24 [Design/#23] 상단바, 로그인 후 화면 퍼블리싱
  index.html
  public/images/logout.svg
  public/images/person.svg
  public/images/photo.svg
  public/images/profileBg.svg
  public/images/search.svg
  src/App.tsx
  src/components/Navbar.tsx
  src/components/bookshape/Bookmark.tsx
  src/components/bookshape/ClosedBook.tsx
  src/pages/Auth/components/Logout.tsx
  src/pages/Main/MemberMainPage.tsx
  src/pages/Main/components/OpenModal.tsx
  src/styles/bookshape/closedbook.style.ts
  src/styles/common.style.ts
  src/theme/GlobalStyle.ts
  src/theme/theme.ts
Labels: 퍼블리싱

#27 [Design/#26] 일기 목록, 조회, 검색 퍼블리싱
  public/images/cloud.svg
  public/images/rainy.svg
  public/images/share.svg
  public/images/snow.svg
  public/images/sunny.svg
  public/images/update.svg
  public/images/write.PNG
  public/images/write.svg
  src/App.tsx
  src/components/Navbar.tsx
  src/components/bookshape/BookShapeL.tsx
  src/components/bookshape/BookShapeR.tsx
  src/components/bookshape/Bookmark.tsx
  src/components/bookshape/ClosedBook.tsx
  src/components/bookshape/OpenBookLeft.tsx
  src/components/bookshape/OpenBookRight.tsx
  src/pages/DiaryList/GrimListPage.tsx
  src/pages/DiaryList/components/Calender.css
  src/pages/DiaryList/components/Calender.tsx
  src/pages/DiaryList/components/DiaryList.tsx
  src/pages/DiaryList/components/ResultManuscript.tsx
  src/pages/Main/MemberMainPage.tsx
  src/pages/Manual/ManualPage.tsx
  src/pages/Search/DiarySearchPage.tsx
  src/pages/WriteDiary/WriteGrimPage.tsx
  src/pages/WriteDiary/components/DiaryContent.tsx
  src/pages/WriteDiary/components/Drawing.tsx
  src/pages/WriteDiary/components/Emoji.tsx
  src/pages/WriteDiary/components/GrimChoice.tsx
  src/pages/WriteDiary/components/Manuscript.tsx
  src/styles/bookshape/closedbook.style.ts
  src/styles/bookshape/opendbook.style.ts
  src/styles/diary/diary.style.ts
  src/styles/diary/diarylist.style.ts
  src/styles/diary/diarywrite.style.ts
Labels: 퍼블리싱

#28 [Refactor/#25] 책 넘기는 부분 효과 수정
  src/components/bookshape/ClosedBook.tsx
  src/components/bookshape/Right.css
  src/pages/Auth/SignIn/SignInPage.tsx
  src/pages/Auth/SignIn/components/SignInForm.tsx
  src/pages/Auth/SignUp/SignUpPage.tsx
  src/pages/Main/MemberMainPage.tsx
  src/pages/Main/NonMemberMainPage.tsx
  src/pages/Main/components/Modal.css
  src/styles/auth/auth.style.ts
  src/styles/bookshape/closedbook.style.ts
  src/styles/common.style.ts
  src/theme/theme.ts
Labels: 리팩토링

#30 [Feat/#29] 덮힌 부분 반응형 구현 및 책 넘기기 연결
  src/components/bookshape/ClosedBook.tsx
  src/index.css
  src/pages/Auth/SignIn/components/SignInForm.tsx
  src/pages/Auth/SignUp/components/SignUpForm.tsx
  src/pages/Main/MemberMainPage.tsx
  src/pages/Main/components/Modal.css
  src/styles/auth/auth.style.ts
  src/styles/bookshape/closedbook.style.ts
  src/styles/bookshape/opendbook.style.ts
  src/theme/GlobalStyle.ts
Labels: 기능구현

#37 [Feat/#33] 로딩창 구현
  src/components/Loading.tsx
  src/pages/DiaryList/GrimListPage.tsx
  src/pages/Main/NonMemberMainPage.tsx
  src/pages/WriteDiary/WriteGrimPage.tsx
  src/pages/WriteDiary/components/DiaryContent.tsx
  src/pages/WriteDiary/components/GrimChoice.tsx
  src/styles/diary/diarywrite.style.ts
Labels: 기능구현

#32 [Feat/#31] 펼친 부분(일기 목록, 작성) 반응형 구현
  public/images/cloud.svg
  public/images/rainy.svg
  public/images/share.svg
  public/images/snow.svg
  public/images/sunny.svg
  public/images/update.svg
  src/components/bookshape/Bookmark.tsx
  src/index.css
  src/pages/DiaryList/components/Calender.tsx
  src/pages/DiaryList/components/DiaryList.tsx
  src/pages/WriteDiary/components/DiaryContent.tsx
  src/pages/WriteDiary/components/Drawing.tsx
  src/styles/bookshape/opendbook.style.ts
  src/styles/diary/diary.style.ts
  src/styles/diary/diarylist.style.ts
  src/theme/GlobalStyle.ts
  vite.config.ts
Labels: 기능구현

#35 [Design/#34] 테마 선택 퍼블리싱
  public/images/bluetheme.svg
  public/images/originaltheme.svg
  public/images/palette.svg
  public/images/palette2.svg
  public/images/rainbowtheme.svg
  src/components/Navbar.tsx
  src/components/bookshape/ClosedBook.tsx
  src/styles/bookshape/closedbook.style.ts
  src/theme/GlobalStyle.ts
Labels: 퍼블리싱
