Repository AI-ary/frontend, pull requests merged in 2023-07, with the labels that each got.

#2 [Feat/#1] vite, react-query, tailwind 환경 세팅
  index.html
  package.json
  postcss.config.js
  src/App.tsx
  src/apis/axios.ts
  src/components/Modal/Modal.tsx
  src/components/Modal/OpenModal.tsx
  src/components/access/IsLogin.ts
  src/components/access/Logout.tsx
  src/components/access/PublicPages.tsx
  src/components/account/SignInForm.tsx
  src/components/account/SignUpForm.tsx
  src/components/bookshape/Right.css
  src/components/diary/DiaryContent.tsx
  src/components/diary/Drawing.tsx
  src/components/diary/Manuscript.tsx
  src/components/diarylist/Calender.css
  src/components/diarylist/DiaryList.tsx
  src/index.css
  src/index.tsx
  src/pages/AfterLogin.tsx
  src/pages/GrimList.tsx
  src/pages/Title.tsx
  src/vite-env.d.ts
  tailwind.config.js
  tsconfig.json
  tsconfig.node.json
  vite.config.ts
  yarn.lock
Labels: 환경설정

#8 [Feat/#7] 검색 기능 구현
  public/data/dummy.json
  src/App.tsx
  src/components/bookshape/BookShapeL.tsx
  src/components/bookshape/BookShapeR.tsx
  src/components/bookshape/Right.css
  src/components/diarylist/DiaryList.tsx
  src/components/search/DiarySearch.tsx
  src/index.css
  src/pages/DiarySearchList.tsx
  src/pages/GrimList.tsx
Labels: 기능구현

#6 [Fix/#5] 그림 크기 조절 에러 해결
  src/components/diary/Drawing.tsx
  src/components/diary/Emoji.tsx
  src/components/diary/GrimChoice.tsx
  src/components/diary/Manuscript.tsx
  src/components/diarylist/DiaryList.tsx
  src/pages/ErrorPage.tsx
  src/pages/GrimList.tsx
  yarn.lock
Labels: 오류수정

#15 [Feat/#13] 일기 목록, 작성, 검색 react-query 적용
  src/apis/axios.ts
  src/apis/baseAxios.ts
  src/apis/diaryList.ts
  src/apis/searchDiary.ts
  src/apis/writeDiary.ts
  src/components/Modal/Modal.tsx
  src/components/access/Logout.tsx
  src/components/account/SignInForm.tsx
  src/components/account/SignUpForm.tsx
  src/components/diary/DiaryContent.tsx
  src/components/diarylist/Calender.tsx
  src/components/diarylist/DiaryList.tsx
  src/index.tsx
  src/pages/DiarySearchList.tsx
  src/pages/GrimList.tsx
  src/pages/Root.tsx
Labels: 기능구현

#20 [Feat/#19] 배경&표지 테마 선택시 변경 기능 구현
  package.json
  public/images/bg-blue.svg
  public/images/bg-rainbow.svg
  src/App.tsx
  src/components/Navbar.tsx
  src/components/bookshape/BookCover.tsx
  src/components/bookshape/Bookmark.tsx
  src/components/bookshape/Right.css
  src/index.css
  src/pages/Main/MemberMainPage.tsx
  src/theme/GlobalStyle.ts
  src/theme/theme.ts
  yarn.lock
Labels: 기능구현

#21 [Design/#18] 덮힌 상태 구현
  package.json
  public/images/aiary.png
  public/images/rainbow.png
  src/components/bookshape/ClosedBook.tsx
  src/pages/Auth/SignIn/SignInPage.tsx
  src/pages/Auth/SignIn/components/SignInForm.tsx
  src/pages/Auth/SignUp/SignUpPage.tsx
  src/pages/Auth/SignUp/components/SignUpForm.tsx
  src/pages/Auth/auth.css
  src/pages/Main/NonMemberMainPage.tsx
  src/styles/auth/auth.style.ts
  src/styles/bookshape/closedbook.style.ts
  src/styles/bookshape/opendbook.style.ts
  src/styles/common.style.ts
  src/styles/main/main.style.ts
  yarn.lock
Labels: 퍼블리싱
